CREATE DATABASE "gamescape_db"
  WITH OWNER = postgres
  TEMPLATE template0
  ENCODING 'UTF8';

\c gamescape_db
SELECT current_database();
SET search_path TO public;








--  4) Sätt default search_path (gäller automatiskt vid nya anslutningar)
ALTER DATABASE gamescape_db SET search_path = gamescape, public;

-- (Valfritt) om du vill sätta per user istället:
-- ALTER ROLE ditt_usernamn IN DATABASE gamescape_db SET search_path = gamescape, public;

-- 5) För nuvarande session (om du vill direkt utan att reconnecta)
SET search_path TO gamescape, public;

-- Databasschema – GameScape (PostgreSQL)
SET search_path TO public;
-- nu räcker det att skriva CREATE TABLE game (...)

-- ===== USER =====
CREATE TABLE users (
  user_id     INT SERIAL	 PRIMARY KEY,
  username    VARCHAR(50)  NOT NULL UNIQUE,
  email       VARCHAR(255) NOT NULL UNIQUE,
  password    VARCHAR(255) NOT NULL,
  full_name   VARCHAR(120)	Not null,
  status      VARCHAR(20)  NOT NULL DEFAULT 'offline',
  is_admin    BOOLEAN      NOT NULL DEFAULT FALSE,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  CONSTRAINT users_status_chk CHECK (status IN ('online', 'offline'))
);
ALTER TABLE users
ADD COLUMN birthday DATE NOT NULL,
ADD COLUMN gender VARCHAR(10) NOT NULL,
ADD CONSTRAINT gender_chk CHECK (gender IN ('male', 'female'));
ALTER TABLE users DROP COLUMN birth_date;

-- ===== GAME =====
CREATE TABLE game (
  game_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(120) NOT NULL UNIQUE,
  image_path  VARCHAR(500) NOT NULL
);

-- ===== USER_GAME =====
CREATE TABLE user_game (
  user_game_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      INT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  game_id      INT NOT NULL REFERENCES game(game_id)  ON DELETE CASCADE,
  rank         VARCHAR(60)  NOT NULL,
  platform     VARCHAR(60)  NOT NULL,
  CONSTRAINT user_game_unique UNIQUE (user_id, game_id, platform)
);

-- ===== LOCATION =====
CREATE TABLE location (
  location_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     INT NOT NULL UNIQUE REFERENCES users(user_id) ON DELETE CASCADE,
  ip_address  INET NOT NULL,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ===== EVENT =====
CREATE TABLE event (
  event_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  creator_id        INT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
  game_id           INT REFERENCES game(game_id) ON DELETE SET NULL, -- om event är "ett spel"
  title             VARCHAR(160) NOT NULL,
  datetime          TIMESTAMPTZ  NOT NULL,
  description       TEXT,
  rank_user_game_id INT NULL REFERENCES user_game(user_game_id) ON DELETE SET NULL,
  min_rank          VARCHAR(60),
  max_rank          VARCHAR(60)
);

-- ===== TAG =====
CREATE TABLE tag (
  tag_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name   VARCHAR(60) NOT NULL UNIQUE
);

-- ===== EVENT_GAME (Many-to-Many) =====
CREATE TABLE event_game (
  event_id INT NOT NULL REFERENCES event(event_id) ON DELETE CASCADE,
  game_id  INT NOT NULL REFERENCES game(game_id)  ON DELETE CASCADE,
  PRIMARY KEY (event_id, game_id)
);

-- ===== EVENT_PARTICIPANT =====
CREATE TABLE event_participant (
  event_id   INT NOT NULL REFERENCES event(event_id)  ON DELETE CASCADE,
  user_id    INT NOT NULL REFERENCES users(user_id)   ON DELETE CASCADE,
  joined_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (event_id, user_id)
);

-- ===== EVENT_TAG =====
CREATE TABLE event_tag (
  event_id INT NOT NULL REFERENCES event(event_id) ON DELETE CASCADE,
  tag_id   INT NOT NULL REFERENCES tag(tag_id)     ON DELETE CASCADE,
  PRIMARY KEY (event_id, tag_id)
);

-- ===== MESSAGE =====
CREATE TABLE message (
  message_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id   INT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  receiver_id INT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  content     TEXT NOT NULL,
  "timestamp" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT message_sender_receiver_chk CHECK (sender_id <> receiver_id)
);

-- ===== NOTIFICATION =====
CREATE TABLE notification (
  notification_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         INT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE, -- mottagare
  sender_id       INT REFERENCES users(user_id) ON DELETE SET NULL,         -- avsändare
  type            VARCHAR(30) NOT NULL, -- t.ex. 'chat' / 'event'
  content         TEXT NOT NULL,
  is_read         BOOLEAN NOT NULL DEFAULT FALSE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- (Valfritt) Index för snabbare queries
CREATE INDEX idx_user_game_user_id ON user_game(user_id);
CREATE INDEX idx_user_game_game_id ON user_game(game_id);
CREATE INDEX idx_event_creator_id ON event(creator_id);
CREATE INDEX idx_event_datetime ON event(datetime);
CREATE INDEX idx_message_receiver ON message(receiver_id, "timestamp");
CREATE INDEX idx_notification_user ON notification(user_id, created_at);





SELECT * FROM users 
ALTER TABLE users
ALTER COLUMN full_name SET NOT NULL;
